name: guardbill
description: GuardBill AI Financial Security Scanner.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.12.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 🚨 终极修复：解锁版本封印，使用全面适配 Android 最新环境的新版底层引擎！
  cunning_document_scanner: ^1.4.0
  google_mlkit_text_recognition: ^0.15.1
  shared_preferences: ^2.2.2
  ffi: ^2.1.2
  dio: ^5.4.0
  path_provider: ^2.1.2
  flutter_local_notifications: ^17.0.0

flutter:
  uses-material-design: true